### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by AdamR777** [younesdev1/RevBusinessCardGen#8]
generator fail to login, seems to be issues on passing data

[12:50:22.528] Logging in 

Traceback (most recent call last):
  File "gen.py", line 363, in <module>
    RevGen()
  File "gen.py", line 61, in __init__
    self.login()
  File "gen.py", line 137, in login
    response = self.s.post(
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\cloudscraper\__init__.py", line 244, in request
    (method, url, args, kwargs) = self.requestPreHook(
  File "gen.py", line 103, in pre_hook
    self.s.cookies.set("token", confi.REV_TOKEN, domain="business.revolut.com")
NameError: name 'confi' is not defined

all fields are filled except for "DEVICE_ID" since log details are present.

**Comment by younesdev1** [comment]
got fixed in last push!
